#!/usr/bin/env sh

set -o xtrace

export TRUST_PARAMS=1

tag=${TAG:-debug}

go run -tags=$tag ./cmd/lotus wallet import ~/.genesis-sectors/pre-seal-k01000.key
go run -tags=$tag ./cmd/lotus-storage-miner init --actor=k01000 --genesis-miner --pre-sealed-sectors=~/.genesis-sectors --pre-sealed-metadata=~/.genesis-sectors/pre-seal-k01000.json
